shared:
    image: node:14

jobs:
  A:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  B:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  C:
    requires: [A]
    steps:
      - ok: echo ok
  D:
    requires: [C]
    steps:
      - ok: echo ok
  E:
    requires: [D]
    steps:
      - ok: echo ok
  F:
    requires: [A]
    steps:
      - ok: echo ok
  G:
    requires: [A]
    steps:
      - ok: echo ok
  H:
    requires: [A]
    steps:
      - ok: echo ok
  I:
    requires: [A, H]
    steps:
      - ok: echo ok